### ISSUE TITLE
code blocks wrapping too early

### ISSUE THREAD

**Issue by Leslie-C** [oneilsh/apcb_second_edition#2]
https://github.com/oneilsh/apcb_second_edition/blob/45372ea630a1769bcfdb66a30755a739031cf646/part1-03-command-line-filesystem.Rmd#L213-L221

Some code blocks are wrapping text lines too early - @oneilsh - is there any easy setting to change this?

**Comment by Leslie-C** [comment]
Screenshot for clarity:
![image](https://user-images.githubusercontent.com/1646180/131364033-1f042d81-1728-4dec-95e2-2adbf2cfe905.png)

Should only have two lines of output after `ls` command

**Comment by oneilsh** [comment]
I've noticed that too, I'll look into it. We should be careful to keep the line lengths under 80 chars regardless but this is something different.
